hichip_db_py: "<software-dir>/hichip-db/bin/python"
hic_tls_py: "<software-dir>/hic_tls/bin/python"
hic_tls_R: "<software-dir>/R/bin/Rscript"
R4: "<software-dir>/R-4.0.3/bin/Rscript"
fithic: "<software-dir>/fithic/fithic/fithic.py"
fithic_tls: "<software-dir>/fithic/fithic/fithic_tls.py"
hicpro2fithic: "<software-dir>/fithic/fithic/utils/HiCPro2FitHiC.py"
hicpro_utils: "<software-dir>/HiC-Pro/bin/utils/"
juicer_tools: "<software-dir>/juicer_tools.1.8.9_jcuda.0.8.jar"
Rpath: "<software-dir>/R/bin/R"
CLINES: ["A549", "Caki2", "HEK293", "LNCaP", "NCI-H460", "Panc1", "SKNSH"]
DIXON_HIC_OVERLAPS: ["A549", "Caki2", "LNCaP", "NCI-H460", "Panc1", "SKNSH"]
DIXON_WGS_OVERLAPS: ["A549", "Caki2", "LNCaP", "NCI-H460", "Panc1"]
hictrans: "<software-dir>/HiCtrans/hictrans.v3.R"
hicnv: "<software-dir>/HiCnv/hicnv_v2.R"
hicnv_scripts: "<software-dir>/HiCnv/scripts/"
python2: "<software-dir>/python_2.7.18/bin/python"
mustache: "<software-dir>/mustache/bin/mustache"
mustache_python: "<software-dir>/mustache/bin/python"
juicer_tools_1.13.02: "<software-dir>/juicer_tools_1.13.02.jar"
cooler: "<software-dir>/hic_tls/bin/cooler"
bgzip: "<software-dir>/hic_tls/bin/bgzip"
liftover: "<software-dir>/UCSC_Browser_Tools/liftOver"
hichip_db_python: "<software-dir>/hichip-db/bin/python"
