name: hic_tls
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - bedtools
  - biopython
  - blas
  - bokeh
  - bzip2
  - ca-certificates
  - cairo
  - curl
  - dbus
  - expat
  - fontconfig
  - freetype
  - gettext
  - glib
  - graphite2
  - graphviz
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - htslib
  - icu
  - intel-openmp
  - jpeg
  - krb5
  - libcurl
  - libdeflate
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - libpng
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libtool
  - libuuid
  - libxcb
  - libxml2
  - markupsafe
  - mkl
  - mkl_fft
  - mkl_random
  - mmtf-python
  - msgpack-python
  - ncurses
  - olefile
  - openssl
  - pango
  - parallel
  - patsy
  - pcre
  - pixman
  - pthread-stubs
  - pygraphviz
  - pyqt
  - python
  - qt
  - readline
  - rfmix
  - samtools
  - scikit-learn
  - sip
  - sqlite
  - tk
  - tornado
  - wheel
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxpm
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zlib
  - pip:
    - alembic
    - amply
    - appdirs
    - argcomplete
    - argh
    - argon2-cffi
    - argparse
    - args
    - asciitree
    - async-generator
    - attrs
    - autograd
    - backcall
    - bcrypt
    - biothings-client
    - bleach
    - boto
    - boto3
    - botocore
    - brotli
    - cached-property
    - camelot-py
    - certifi
    - cffi
    - chardet
    - click
    - cliff
    - clint
    - clodius
    - cloudpickle
    - cmaes
    - cmd2
    - colorama
    - coloredlogs
    - colorlog
    - conda
    - connection-pool
    - cooler
    - coverage
    - cryptography
    - cycler
    - cython
    - cytoolz
    - dash
    - dash-core-components
    - dash-cytoscape
    - dash-html-components
    - dash-renderer
    - dash-table
    - dask
    - datacache
    - datrie
    - decorator
    - defusedxml
    - dill
    - diskcache
    - django
    - django-tagging
    - docutils
    - dropbox
    - dtw-python
    - ecdsa
    - entrypoints
    - et-xmlfile
    - ext-sort
    - filechunkio
    - filelock
    - fithic
    - flake8
    - flask
    - flask-compress
    - flask-cors
    - ftputil
    - fusepy
    - future
    - gevent
    - gffutils
    - gitdb
    - gitpython
    - greenlet
    - gtfparse
    - h5py
    - hic-straw
    - hicmatrix
    - higlass-python
    - httplib2
    - humanfriendly
    - humanize
    - hyperopt
    - iced
    - idna
    - imageio
    - iml
    - importlib-metadata
    - iniconfig
    - interpret
    - interpret-core
    - intervaltree
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - itsdangerous
    - jdcal
    - jedi
    - jinja2
    - jmespath
    - joblib
    - jsonpointer
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyterlab-pygments
    - kiwisolver
    - lasagne
    - lime
    - llvmlite
    - lzstring
    - mako
    - markdown
    - marshmallow
    - matplotlib
    - matplotlib-venn
    - mccabe
    - memoized-property
    - mistune
    - mock
    - mofapy2
    - multiprocess
    - multiqc
    - mygene
    - nbclient
    - nbconvert
    - nbformat
    - negspy
    - nest-asyncio
    - nested-cv
    - networkx
    - nolearn
    - nose
    - notebook
    - numba
    - numexpr
    - numpy
    - oauthlib
    - opencv-contrib-python-headless
    - opencv-python
    - openpyxl
    - optuna
    - packaging
    - pairtools
    - pandas
    - pandocfilters
    - parameters
    - paramiko
    - parso
    - pastis
    - pbr
    - pdfminer-six
    - pexpect
    - pickleshare
    - pillow
    - pip
    - plotly
    - pluggy
    - prettytable
    - progressbar33
    - prometheus-client
    - prompt-toolkit
    - psutil
    - ptyprocess
    - pulp
    - py
    - pyasn1
    - pybbi
    - pybedtools
    - pybigwig
    - pybind11
    - pycodestyle
    - pycosat
    - pycparser
    - pyensembl
    - pyfaidx
    - pyflakes
    - pygenometracks
    - pygltools
    - pygments
    - pygtrie
    - pynacl
    - pypairix
    - pyparsing
    - pypdf2
    - pyperclip
    - pypts
    - pyrsistent
    - pysam
    - pysftp
    - pytest
    - python-dateutil
    - python-editor
    - python-graphviz
    - pytz
    - pywavelets
    - pyyaml
    - pyzmq
    - ratelimiter
    - reportlab
    - requests
    - retrying
    - rpy2
    - rsa
    - ruamel-yaml
    - ruamel-yaml-clib
    - s3transfer
    - salib
    - scikit-image
    - scipy
    - seaborn
    - send2trash
    - serializable
    - setuptools
    - sh
    - shap
    - simdna
    - simple-httpfs
    - simplejson
    - six
    - sklearn
    - skope-rules
    - slicer
    - slugid
    - smart-open
    - smmap
    - snakemake
    - sortedcontainers
    - spectra
    - sqlalchemy
    - statsmodels
    - stevedore
    - stopit
    - strawc
    - sumatra
    - tables
    - tabulate
    - tenacity
    - terminado
    - testpath
    - theano
    - tifffile
    - tinytimer
    - toml
    - toolz
    - toposort
    - tqdm
    - traitlets
    - treeinterpreter
    - typechecks
    - typing-extensions
    - tzlocal
    - upsetplot
    - urllib3
    - wcwidth
    - webencodings
    - websocket-client
    - werkzeug
    - widgetsnbextension
    - wrapt
    - xgboost
    - xlrd
    - xmltodict
    - zipp
    - zope-event
    - zope-interface
